// Generated by scripts/catalog-cast.mjs. Immutable Milo-family asset URLs.
export const CAST_MODEL_URLS = {
  "foxy": "/models/foxy-milo-family-e853dbc5b018.glb",
  "dog": "/models/dog-milo-family-e14d17c69d0d.glb",
  "lion": "/models/lion-milo-family-743b159a1993.glb",
  "bunny": "/models/bunny-milo-family-caa8acc56d27.glb",
  "bear": "/models/bear-milo-family-8bef817e507e.glb",
  "panda": "/models/panda-milo-family-6c543bd2aff1.glb",
  "elephant": "/models/elephant-milo-family-ca9e69c609ae.glb"
} as const;
