import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';

const ids = ['foxy', 'cat', 'dog', 'lion', 'bunny', 'bear', 'panda', 'elephant'];
const models = [];
const urls = {};
for (const id of ids) {
  const info = JSON.parse(await readFile(`public/models/${id}-master-info.json`, 'utf8'));
  const data = await readFile(`public/models/${info.asset}`);
  if (createHash('sha256').update(data).digest('hex') !== info.sha256)
    throw Error(`${id}: hash mismatch`);
  if (id !== 'cat') urls[id] = `/models/${info.asset}`;
  models.push({ id, ...info });
}
await writeFile(
  'src/characters/castAssets.ts',
  '// Generated by scripts/catalog-cast.mjs. Immutable Milo-family asset URLs.\n' +
    `export const CAST_MODEL_URLS = ${JSON.stringify(urls, null, 2)} as const;\n`,
);
await writeFile(
  'public/models/catalog.json',
  JSON.stringify(
    {
      format: 'glTF 2.0',
      source: 'Blender Milo-family production pipeline',
      note: 'Milo v9: original body meshes/maps and seven clips, clean short fur, 23 joints (25 for elephant), soft ear/trunk controls, compact morph normal noise. Original CAT v8 remains archived. Sunny uses the supplied Cozy Cub lion; Maple derives from the panda with a fur-only atlas repaint.',
      models,
    },
    null,
    2,
  ) + '\n',
);
console.log(
  `Cataloged ${models.length} authored models; ${(models.reduce((n, m) => n + m.bytes, 0) / 1048576).toFixed(1)} MiB total`,
);
