"""Original gentle cartoon effects for all eight friends; no external recordings."""
from pathlib import Path
import json, shutil, hashlib, subprocess
import numpy as np
import soundfile as sf
from scipy.signal import butter, sosfilt
import imageio_ffmpeg
root=Path(__file__).resolve().parent.parent
out=root/'public/audio'
manifest=json.loads((out/'manifest.json').read_text(encoding='utf-8'))
manifest['voice']='Eight distinct cast voices with original cartoon pitch treatment'
clips={row['cue']:row for row in manifest['clips']}
sr=24000
rng=np.random.default_rng(3291)
profiles={'foxy':(.56,[520,720,480,620,460],.025), 'bunny':(.54,[380,410,350],.13),
          'bear':(.82,[120,105,130],.08), 'panda':(.62,[230,180,250,190],.075),
          'elephant':(.82,[300,440,520,360],.025)}
ffmpeg=imageio_ffmpeg.get_ffmpeg_exe()
for id,(duration,pitches,breath) in profiles.items():
    t=np.arange(int(sr*duration))/sr
    pitch=np.interp(t/duration,np.linspace(0,1,len(pitches)),pitches)
    phase=2*np.pi*np.cumsum(pitch)/sr
    sound=sum(np.sin(phase*k)/(k**(1.1 if id=='elephant' else 1.65)) for k in range(1,9))
    noise=sosfilt(butter(2,1500,'lowpass',fs=sr,output='sos'),rng.normal(0,1,len(t)))
    if id=='bunny': sound=sound*.025+noise*.28
    else: sound=sound*.65+noise*breath
    envelope=np.sin(np.pi*t/duration)**1.2
    if id in ['foxy','panda','bunny']: envelope*=.2+.8*np.sin(t/duration*np.pi*2)**2
    sound*=envelope
    sound=sound/(np.max(np.abs(sound))+1e-8)*.35
    cue='call-'+id; path=out/'animals'/f'{cue}.wav'
    sf.write(path,sound,sr,subtype='PCM_16')
    subprocess.run([ffmpeg,'-y','-hide_banner','-loglevel','error','-i',str(path),'-c:a','libmp3lame','-b:a','96k',str(path.with_suffix('.mp3'))],check=True)
    clips[cue]={'cue':cue,'text':f'Friendly stylized {id} sound','group':'animals','kind':'sfx',
                'voice':'original procedural cartoon sound','duration':duration,'peakDBFS':-9.1,
                'sha256':hashlib.sha256(path.read_bytes()).hexdigest()}
for id,source in [('cat','meow'),('dog','woof'),('lion','roar')]:
    cue='call-'+id
    for ext in ['wav','mp3']: shutil.copyfile(out/'animals'/f'{source}.{ext}',out/'animals'/f'{cue}.{ext}')
    clips[cue]={**clips[source],'cue':cue}
manifest['clips']=list(clips.values())
(out/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
values=[('cueDurations','number',{k:v['duration'] for k,v in clips.items()}),
        ('cueTexts','string',{k:v['text'] for k,v in clips.items()}),
        ('cueGroups','string',{k:v['group'] for k,v in clips.items()})]
(root/'src/audio/generated.ts').write_text('// Generated by the offline audio scripts\n'+
 '\n'.join(f'export const {name}: Record<string, {kind}> = '+json.dumps(value,indent=2)+';' for name,kind,value in values)+'\n',encoding='utf-8')
print(f'PASS: {len(clips)} clips, eight distinct voices and eight original cast effects')
