export const markerVersion = 'milo-v2';
export const markerDirectory = `public/markers/${markerVersion}`;
export const cards = [
  {
    id: 'cat',
    word: 'CAT',
    name: 'Milo',
    color: '#b897cc',
    dark: '#50415d',
    seed: 17,
    reference: 'assets/characters/cat/concepts/milo-turnaround-v1.png',
  },
  {
    id: 'dog',
    word: 'DOG',
    name: 'Bubbles',
    color: '#9ccad5',
    dark: '#304f66',
    seed: 43,
    reference: 'assets/characters/cast/concepts/bubbles-turnaround-v1.png',
  },
  {
    id: 'lion',
    word: 'LION',
    name: 'Sunny',
    color: '#efce87',
    dark: '#745031',
    seed: 83,
    reference: 'assets/characters/cast/concepts/sunny-turnaround-v1.png',
  },
  {
    id: 'foxy',
    word: 'FOX',
    name: 'Foxy',
    color: '#efa77b',
    dark: '#743e32',
    seed: 109,
    reference: 'assets/characters/cast/concepts/foxy-turnaround-v2.png',
  },
  {
    id: 'bunny',
    word: 'RABBIT',
    name: 'Poppy',
    color: '#edc4ce',
    dark: '#733e5b',
    seed: 137,
    reference: 'assets/characters/cast/concepts/poppy-turnaround-v1.png',
  },
  {
    id: 'bear',
    word: 'BEAR',
    name: 'Maple',
    color: '#bd936f',
    dark: '#584334',
    seed: 173,
    reference: 'assets/characters/cast/concepts/maple-turnaround-v1.png',
  },
  {
    id: 'panda',
    word: 'PANDA',
    name: 'Pebble',
    color: '#ced7cd',
    dark: '#394b45',
    seed: 211,
    reference: 'assets/characters/cast/concepts/pebble-turnaround-v2.png',
  },
  {
    id: 'elephant',
    word: 'ELEPHANT',
    name: 'Ellie',
    color: '#a5b9d5',
    dark: '#3d4e72',
    seed: 251,
    reference: 'assets/characters/cast/concepts/ellie-turnaround-v1.png',
  },
];
